services:
  web:
    volumes:
      - ..:/app
      - ../.devcontainer:/karakeep-devcontainer:ro
      - node_modules:/app/node_modules
      - data:/data
  workers:
    volumes:
      - ..:/app
      - ../.devcontainer:/karakeep-devcontainer:ro
      - node_modules:/app/node_modules
      - data:/data
  prep:
    volumes:
      - ..:/app
      - ../.devcontainer:/karakeep-devcontainer:ro
      - node_modules:/app/node_modules
      - data:/data
  meilisearch:
  chrome:

volumes:
  node_modules:
